declare module 'redux-saga-routines' {
/** Declaration file generated by dts-gen */

export function bindRoutineCreators(routineCreators: any, dispatch: any): any;

export function createRoutine(...args: any[]): any;

export function routinesWatcherSaga(): any;

export namespace bindRoutineCreators {
    const prototype: {
    };

}

export namespace createRoutine {
    const prototype: {
    };

}

export namespace routinesWatcherSaga {
    namespace prototype {
        function next(arg: any): any;

        function toString(): any;

        namespace next {
            const prototype: {
            };

        }

        namespace toString {
            const prototype: {
            };

        }

    }

}

}
